############################
# Fuente
############################

font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15

############################
# Cursor
############################

cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15

############################
# Ventana
############################

window_padding_width 12
placement_strategy center
remember_window_size yes
confirm_os_window_close 0

############################
# Transparencia
############################

background_opacity 0.92
background_blur 32

############################
# Scroll
############################

scrollback_lines 10000

############################
# Copiar
############################

copy_on_select yes
strip_trailing_spaces smart

############################
# Sonido
############################

enable_audio_bell no

############################
# Ligaduras
############################

disable_ligatures never

############################
# Shell
############################

shell_integration enabled

############################
# Tema
############################

include current-theme.conf

########################################
# Amethyst Sky
########################################

foreground              #E6E9F2
background              #16161F

selection_foreground    #16161F
selection_background    #F5B3C7

cursor                  #CBA6F7
cursor_text_color       #16161F

url_color               #89B4FA

active_border_color     #CBA6F7
inactive_border_color   #3B3E59

active_tab_background   #CBA6F7
active_tab_foreground   #16161F

inactive_tab_background #26263A
inactive_tab_foreground #AEB6D9

color0  #45475A
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #CBA6F7
color6  #74D8F5
color7  #CDD6F4

color8  #6C7086
color9  #F5B3C7
color10 #B8F2B0
color11 #FFE8B3
color12 #A7CCFF
color13 #D8B8FF
color14 #8AE5FF
color15 #F4F6FF
