function fish_prompt
    set_color br_magenta
    printf "%s" (whoami)

    set_color br_blue
    printf "@%s " (prompt_hostname)

    set_color br_cyan
    prompt_pwd

    echo

    set_color "#ff79c6"
    printf "❯ "

    set_color normal
end
